apiVersion: apps/v1
kind: Deployment
metadata:
  name: clovider-fe
  labels:
    app: clovider-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clovider-app
  template:
    metadata:
      labels:
        app: clovider-app
    spec:
      containers:
      - image: 
        name: 
        ports:
        - containerPort: 3000
          name: http
      imagePullSecrets:
      - name: kic-registry