apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clovider-app
  namespace: clovider
spec:
  project: default
  source:
    repoURL: https://github.com/CLOVIDER/kic-k8s"
    targetRevision: main
    path: "clovider-app"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
