apiVersion: apps/v1
kind: Deployment
metadata:
  name: clovider-be-deployment
  namespace: clovider
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: clovider-api
  template:
    metadata:
      labels:
        app: clovider-api
    spec:
      containers:
        - image: 'kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-be-app:9376418341978c63e5786c96eb2c6a8b7479c412'
          name: clovider-be-app
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: clovider-registry
