apiVersion: apps/v1
kind: Deployment
metadata:
  name: clovider-be-deployment
  namespace: clovider
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: clovider-api
  template:
    metadata:
      labels:
        app: clovider-api
    spec:
      containers:
      - image: kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-be-app:6db60eda84f7f505a459ba3e070a45ad2f762dd2
        name: clovider-be-app
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"
      imagePullSecrets:
      - name: clovider-registry
