apiVersion: v1
kind: Service
metadata:
  name: clovider-be-service
  namespace: clovider
spec:
  selector:
    app: clovider-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
