apiVersion: apps/v1
kind: Deployment
metadata:
  name: clovider-fe-deployment
  namespace: clovider
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: clovider-app
  template:
    metadata:
      labels:
        app: clovider-app
    spec:
      containers:
      - image: kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-fe-app:8fb85d97473497781bf80d85360e6c3108422bd9
        name: clovider-fe-app
        ports:
        - containerPort: 3000
          name: http
      imagePullSecrets:
      - name: clovider-registry
