apiVersion: apps/v1
kind: Deployment
metadata:
  name: clovider-fe-deployment
  namespace: clovider
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: clovider-app
  template:
    metadata:
      labels:
        app: clovider-app
    spec:
      containers:
        - image: kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-fe-app:2f664a1f89cb2f9fb26c68a1a3c671255c8bcfe2
          name: clovider-fe-app
          ports:
            - containerPort: 3000
              name: http
      imagePullSecrets:
        - name: clovider-registry
