apiVersion: v1
kind: Service
metadata:
  name: clovider-fe-service
  namespace: clovider
spec:
  selector:
    app: clovider-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
